export const TABLEAU_DASHBOARD_DATA = [
  {
    workbookRepoUrl: "CovidDashboard_16541499843110",
    title: "Covid Dashboard",
    defaultViewName: "NationalOverview",
    viewCount: 45,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "CovidDashboard_16541499843110/sheets/NationalOverview",
  },
  {
    workbookRepoUrl: "GLVarienceAnalysis",
    title: "GL Varience Analysis",
    defaultViewName: "FinanceVarianceAnalysisDashboard",
    viewCount: 18,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "GLVarienceAnalysis/sheets/FinanceVarianceAnalysisDashboard",
  },
  {
    workbookRepoUrl: "HRKPIBoxforDetails",
    title: "HR KPI Box for Details",
    defaultViewName: "9BoxEmployeeRatings",
    viewCount: 40,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HRKPIBoxforDetails/sheets/9BoxEmployeeRatings",
  },
  {
    workbookRepoUrl: "HRDashboardExeLook",
    title: "HR Dashboard Exe Look",
    defaultViewName: "HRDASHBOARD",
    viewCount: 15,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HRDashboardExeLook/sheets/HRDASHBOARD",
  },
  {
    workbookRepoUrl: "HRDashboard_16541450471900",
    title: "HR Dashboard",
    defaultViewName: "Overview",
    viewCount: 13,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HRDashboard_16541450471900/sheets/Overview",
  },
  {
    workbookRepoUrl: "HREmployeeDemography",
    title: "HR Employee Demography",
    defaultViewName: "EmployeeDemography",
    viewCount: 19,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HREmployeeDemography/sheets/EmployeeDemography",
  },
  {
    workbookRepoUrl: "HRDashboardforAttrition",
    title: "HR Dashboard for Attrition ",
    defaultViewName: "AttritionSummary",
    viewCount: 23,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HRDashboardforAttrition/sheets/AttritionSummary",
  },
  {
    workbookRepoUrl: "HRKPIforExecutive",
    title: "HR KPI for Executive",
    defaultViewName: "ExecutiveDashboardNew",
    viewCount: 53,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "HRKPIforExecutive/sheets/ExecutiveDashboardNew",
  },
  {
    workbookRepoUrl: "FinanceGLDashboard",
    title: "Finance GL Dashboard",
    defaultViewName: "ExecSummary",
    viewCount: 23,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "FinanceGLDashboard/sheets/ExecSummary",
  },
  {
    workbookRepoUrl: "FinancePLExecutive",
    title: "Finance P&L Executive",
    defaultViewName: "PLDetail",
    viewCount: 24,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "FinancePLExecutive/sheets/PLDetail",
  },
  {
    workbookRepoUrl: "CashFlowSummary",
    title: "Cash Flow Summary",
    defaultViewName: "Whereisthemoney",
    viewCount: 23,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "CashFlowSummary/sheets/Whereisthemoney",
  },
  {
    workbookRepoUrl: "LedgerTransactions",
    title: "Ledger Transactions",
    defaultViewName: "CashFlowDashboardTransactionDetails",
    viewCount: 14,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "LedgerTransactions/sheets/CashFlowDashboardTransactionDetails",
  },
  {
    workbookRepoUrl: "CashFlowReportSample",
    title: "Cash Flow Report Sample",
    defaultViewName: "CashFlowDashboardRunningBalances",
    viewCount: 18,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "CashFlowReportSample/sheets/CashFlowDashboardRunningBalances",
  },
  {
    workbookRepoUrl: "CashFlowSample1",
    title: "Cash Flow Sample1",
    defaultViewName: "CashFlowDashboardSummary",
    viewCount: 17,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "CashFlowSample1/sheets/CashFlowDashboardSummary",
  },
  {
    workbookRepoUrl: "CloudAWSCostandUsage",
    title: "Cloud (AWS) Cost and Usage",
    defaultViewName: "MonthlyCloudOverview",
    viewCount: 47,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "CloudAWSCostandUsage/sheets/MonthlyCloudOverview",
  },
  {
    workbookRepoUrl: "TravelVistorstoAirport",
    title: "Travel Vistors to Airport",
    defaultViewName: "Statewide",
    viewCount: 7,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "TravelVistorstoAirport/sheets/Statewide",
  },
  {
    workbookRepoUrl: "TravelDashboardAIR",
    title: "Travel Dashboard (AIR)",
    defaultViewName: "Dashboard1",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "TravelDashboardAIR/sheets/Dashboard1",
  },
  {
    workbookRepoUrl: "PieProgress",
    title: "Pie Progress ",
    defaultViewName: "ProgressPieCharts",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "PieProgress/sheets/ProgressPieCharts",
  },
  {
    workbookRepoUrl: "PyramidChart_16541437781670",
    title: "Pyramid Chart",
    defaultViewName: "Dashboard1",
    viewCount: 7,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "PyramidChart_16541437781670/sheets/Dashboard1",
  },
  {
    workbookRepoUrl: "SunburstExample_16541435548280",
    title: "Sunburst Example",
    defaultViewName: "Sunburst",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "SunburstExample_16541435548280/sheets/Sunburst",
  },
  {
    workbookRepoUrl: "PromotionCampaignAnalysis",
    title: "Promotion Campaign Analysis",
    defaultViewName: "PromotionCampaignAnalytics",
    viewCount: 19,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "PromotionCampaignAnalysis/sheets/PromotionCampaignAnalytics",
  },
  {
    workbookRepoUrl: "TryingforSunburstbutenededupwiththisforProjectstatus",
    title: "Trying for Sunburst but eneded up with this for Project status",
    defaultViewName: "ProgramStatus",
    viewCount: 13,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "TryingforSunburstbutenededupwiththisforProjectstatus/sheets/ProgramStatus",
  },
  {
    workbookRepoUrl: "KnowtheProjectStatus",
    title: "Know the Project Status",
    defaultViewName: "Dashboard2",
    viewCount: 22,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "KnowtheProjectStatus/sheets/Dashboard2",
  },
  {
    workbookRepoUrl: "DataQualityCheckReport",
    title: "Data Quality Check Report",
    defaultViewName: "CoCOverviewDashboard",
    viewCount: 132,
    numberOfFavorites: 1,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "DataQualityCheckReport/sheets/CoCOverviewDashboard",
  },
  {
    workbookRepoUrl: "SalesSample_16541429613170",
    title: "Sales Sample",
    defaultViewName: "CompleteDashboard",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "SalesSample_16541429613170/sheets/CompleteDashboard",
  },
  {
    workbookRepoUrl: "FunnelExample",
    title: "Funnel Example",
    defaultViewName: "FunnelDashboard",
    viewCount: 8,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "FunnelExample/sheets/FunnelDashboard",
  },
  {
    workbookRepoUrl: "SalesPerformanceOld",
    title: "Sales Performance Old",
    defaultViewName: "SalesPerformance",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "SalesPerformanceOld/sheets/SalesPerformance",
  },
  {
    workbookRepoUrl: "SalesPerformance_16541423572490",
    title: "Sales Performance",
    defaultViewName: "viz_",
    viewCount: 6,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "SalesPerformance_16541423572490/sheets/viz_",
  },
  {
    workbookRepoUrl: "SalesLeadAccountTracker",
    title: "Sales Lead & Account Tracker",
    defaultViewName: "LeadAccountActivityTracking",
    viewCount: 19,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl:
      "SalesLeadAccountTracker/sheets/LeadAccountActivityTracking",
  },
  {
    workbookRepoUrl: "MySalesDashboard_2",
    title: "My Sales Dashboard",
    defaultViewName: "Dashboard1",
    viewCount: 80,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "MySalesDashboard_2/sheets/Dashboard1",
  },
  {
    workbookRepoUrl: "TechnoTalent_Workbook2",
    title: "TechnoTalent.Workbook2",
    defaultViewName: "Map",
    viewCount: 56,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "TechnoTalent_Workbook2/sheets/Map",
  },
  {
    workbookRepoUrl: "TechnoTalentWorkbook",
    title: "TechnoTalent Workbook",
    defaultViewName: "Sheet11",
    viewCount: 71,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "TechnoTalentWorkbook/sheets/Sheet11",
  },
  {
    workbookRepoUrl: "Varun_Sudakar_Workbook",
    title: "Varun_Sudakar_Workbook",
    defaultViewName: "Dashboard4",
    viewCount: 38,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "Varun_Sudakar_Workbook/sheets/Dashboard4",
  },
  {
    workbookRepoUrl: "T_RegionalSalesbyColin",
    title: "T.Regional Sales by Colin",
    defaultViewName: "RegionalSales",
    viewCount: 46,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "T_RegionalSalesbyColin/sheets/RegionalSales",
  },
  {
    workbookRepoUrl: "Assesment1",
    title: "Assesment1",
    defaultViewName: "Dashboard1",
    viewCount: 37,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "Assesment1/sheets/Dashboard1",
  },
  {
    workbookRepoUrl: "TrainingWorksheetsViews",
    title: "Training Worksheets(Views)",
    defaultViewName: "GroupvsSet",
    viewCount: 91,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "TrainingWorksheetsViews/sheets/GroupvsSet",
  },
  {
    workbookRepoUrl: "SRSampleDelta",
    title: "SR Sample Delta",
    defaultViewName: "Dashboard1",
    viewCount: 30,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "SRSampleDelta/sheets/Dashboard1",
  },
  {
    workbookRepoUrl: "ABU_Dashboard",
    title: "ABU_Dashboard",
    defaultViewName: "Orders_Bucketize",
    viewCount: 50,
    numberOfFavorites: 0,
    authorDisplayName: "VENKAT",
    authorProfileName: "venkat5345",
    defaultViewRepoUrl: "ABU_Dashboard/sheets/Orders_Bucketize",
  },
];
